# Generated by Django 2.2.4 on 2019-10-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户详情', 'verbose_name_plural': '用户详情'},
        ),
    ]
