# Generated by Django 2.2.4 on 2019-11-30 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户详情', 'verbose_name_plural': '用户详情'},
        ),
        migrations.AddField(
            model_name='profile',
            name='active_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_type',
            field=models.CharField(blank=True, choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
